<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class EmpDepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $departments = [
            [
                'department_name' => 'Sales',
                'department_code' => 'SALES',
                'description' => 'Handles sales operations and client acquisition',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => 'Primary revenue-generating department',
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Marketing',
                'department_code' => 'MKT',
                'description' => 'Manages marketing campaigns and brand promotion',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => null,
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Human Resources',
                'department_code' => 'HR',
                'description' => 'Oversees recruitment, training, and employee relations',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => 'Handles employee onboarding and compliance',
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Information Technology',
                'department_code' => 'IT',
                'description' => 'Manages IT infrastructure and software development',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => null,
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Finance',
                'department_code' => 'FIN',
                'description' => 'Handles budgeting, accounting, and financial reporting',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => 'Ensures financial compliance and reporting',
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Operations',
                'department_code' => 'OPS',
                'description' => 'Manages day-to-day operational activities and logistics',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => null,
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Customer Support',
                'department_code' => 'CS',
                'description' => 'Provides support and assistance to customers',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => 'Handles customer queries and complaints',
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Research and Development',
                'department_code' => 'RND',
                'description' => 'Focuses on product innovation and development',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => null,
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Legal',
                'department_code' => 'LGL',
                'description' => 'Manages legal compliance and contracts',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => 'Oversees legal agreements and disputes',
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Administration',
                'department_code' => 'ADM',
                'description' => 'Handles administrative tasks and office management',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => null,
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'department_name' => 'Production',
                'department_code' => 'PROD',
                'description' => 'Handles production tasks',
                // 'organizational_unit_id' => 1,
                'created_by_user_id' => 1,
                'updated_by_user_id' => 1,
                'deleted_by_user_id' => null,
                'is_active' => true,
                'is_deleted' => false,
                'remark' => null,
                'department_head_id' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        // Insert departments into the emp_departments table
        DB::table('emp_departments')->insert($departments);
    }
}
